import React, { useState, useEffect } from 'react';
import { DamlLedger, useStreamQueries } from '@c7/react';
import { BridgeWidget } from './BridgeWidget';
import { getConfig } from './bridgeService';
import type { AppConfig, LedgerConfig } from './bridgeService';

// This is a simplified view of the IOU template.
// In a real project, these types would be generated by `dpm codegen-js`.
type Iou = {
  issuer: string;
  owner: string;
  currency: string;
  amount: string;
  observers: string[];
};

// This is a simplified view of the Wrapped Asset template.
type WrappedAsset = {
  notary: string;
  owner: string;
  originalIssuer: string;
  originalOwner: string;
  currency: string;
  amount: string;
  sourceDomainId: string;
};

const AssetTable: React.FC<{
  assets: any[];
  headers: string[];
  rowBuilder: (asset: any) => React.ReactNode;
  title: string;
}> = ({ assets, headers, rowBuilder, title }) => (
  <div className="asset-table-container">
    <h4>{title}</h4>
    {assets.length > 0 ? (
      <table>
        <thead>
          <tr>
            {headers.map(h => <th key={h}>{h}</th>)}
          </tr>
        </thead>
        <tbody>
          {assets.map(rowBuilder)}
        </tbody>
      </table>
    ) : (
      <p>No assets found.</p>
    )}
  </div>
);

const SourceAssetsView: React.FC = () => {
  // NOTE: Replace 'Iou:Iou' with your actual source asset template ID
  const { contracts, loading } = useStreamQueries<Iou>({ template: 'Iou:Iou' });

  if (loading) return <div>Loading source assets...</div>;

  return (
    <AssetTable
      title="Original Assets"
      assets={contracts}
      headers={['Currency', 'Amount', 'Issuer']}
      rowBuilder={(c) => (
        <tr key={c.contractId}>
          <td>{c.payload.currency}</td>
          <td>{parseFloat(c.payload.amount).toFixed(2)}</td>
          <td>{c.payload.issuer.split('::')[0]}</td>
        </tr>
      )}
    />
  );
};

const TargetAssetsView: React.FC = () => {
  // NOTE: Replace with your actual wrapped asset template ID from the bridge model
  const { contracts, loading } = useStreamQueries<WrappedAsset>({ template: 'Bridge.Wrapped:Asset' });

  if (loading) return <div>Loading wrapped assets...</div>;

  return (
    <AssetTable
      title="Wrapped Assets"
      assets={contracts}
      headers={['Currency', 'Amount', 'Source Domain']}
      rowBuilder={(c) => (
        <tr key={c.contractId}>
          <td>{c.payload.currency}</td>
          <td>{parseFloat(c.payload.amount).toFixed(2)}</td>
          <td>{c.payload.sourceDomainId}</td>
        </tr>
      )}
    />
  );
};


const DomainView: React.FC<{ config: LedgerConfig; title: string; children: React.ReactNode }> = ({ config, title, children }) => (
  <DamlLedger party={config.party} token={config.token} httpBaseUrl={config.httpBaseUrl}>
    <div className="domain-panel">
      <h3>{title}</h3>
      <p className="party-id">Party: {config.party.split('::')[0]}</p>
      {children}
    </div>
  </DamlLedger>
);

const App: React.FC = () => {
  const [config, setConfig] = useState<AppConfig | null>(null);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    const fetchAppConfig = async () => {
      try {
        const appConfig = await getConfig();
        setConfig(appConfig);
      } catch (e) {
        console.error("Failed to fetch application configuration:", e);
        setError("Could not connect to bridge services. Please ensure the backend is running and configured correctly.");
      }
    };
    fetchAppConfig();
  }, []);

  if (error) {
    return <div className="app-container error-state"><h1>Error</h1><p>{error}</p></div>;
  }

  if (!config) {
    return <div className="app-container loading-state"><h1>Canton Cross-Chain Bridge</h1><p>Loading configuration...</p></div>;
  }

  return (
    <>
      <style>{`
        :root {
          --primary-bg: #f8f9fa;
          --panel-bg: #ffffff;
          --border-color: #dee2e6;
          --text-color: #212529;
          --primary-color: #003b5c;
          --header-bg: #002b42;
          --header-color: #ffffff;
          --font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif;
        }
        body { margin: 0; font-family: var(--font-family); background-color: var(--primary-bg); color: var(--text-color); }
        .app-container { display: flex; flex-direction: column; height: 100vh; }
        .app-header { background-color: var(--header-bg); color: var(--header-color); padding: 1rem 2rem; text-align: center; }
        .app-header h1 { margin: 0; font-size: 1.5rem; }
        .main-content { display: flex; flex-grow: 1; padding: 2rem; gap: 2rem; flex-wrap: wrap; justify-content: center; align-items: flex-start; }
        .bridge-widget-container { flex-basis: 100%; max-width: 800px; margin: 0 auto 2rem auto; }
        .domain-views-container { display: flex; flex-grow: 1; gap: 2rem; width: 100%; justify-content: center; flex-wrap: wrap; }
        .domain-panel { background-color: var(--panel-bg); border: 1px solid var(--border-color); border-radius: 8px; padding: 1.5rem; flex: 1; min-width: 400px; max-width: 600px; box-shadow: 0 2px 4px rgba(0,0,0,0.05); }
        .domain-panel h3 { margin-top: 0; color: var(--primary-color); border-bottom: 2px solid var(--primary-color); padding-bottom: 0.5rem; }
        .party-id { font-size: 0.8rem; color: #6c757d; margin-bottom: 1.5rem; font-family: monospace; }
        .loading-state, .error-state { display: flex; flex-direction: column; justify-content: center; align-items: center; height: 100vh; text-align: center; }
        .error-state p { color: #dc3545; }
        .asset-table-container h4 { margin-top: 1.5rem; margin-bottom: 0.5rem; }
        table { width: 100%; border-collapse: collapse; }
        th, td { text-align: left; padding: 0.75rem; border-bottom: 1px solid var(--border-color); }
        th { font-weight: 600; }
        tbody tr:last-child td { border-bottom: none; }
      `}</style>
      <div className="app-container">
        <header className="app-header">
          <h1>Canton Cross-Chain Bridge</h1>
        </header>
        <main className="main-content">
          <div className="bridge-widget-container">
            <BridgeWidget sourceConfig={config.source} targetConfig={config.target} />
          </div>
          <div className="domain-views-container">
            <DomainView config={config.source} title="Source Domain">
              <SourceAssetsView />
            </DomainView>
            <DomainView config={config.target} title="Target Domain">
              <TargetAssetsView />
            </DomainView>
          </div>
        </main>
      </div>
    </>
  );
};

export default App;