import React, { useMemo } from 'react';
import { useParty, useStreamQueries } from '@c7/react';
import { Contract } from '@c7/ledger';

// NOTE: These types would typically be generated by `dpm codegen-js`.
// We define them here for type safety within the component.
// The template names are inferred from the project structure.
// Main:LockRequest, Main:LockedAsset, etc.
const LOCK_REQUEST_TID = "Main:LockRequest";
const LOCKED_ASSET_TID = "Main:LockedAsset";
const MINT_REQUEST_TID = "Main:MintRequest";
const MINTED_ASSET_TID = "Main:MintedAsset";
const BURN_REQUEST_TID = "Main:BurnRequest";
const BURNED_RECEIPT_TID = "Main:BurnedReceipt";
const UNLOCK_REQUEST_TID = "BurnRedemption:UnlockRequest";

interface AssetId {
  symbol: string;
  issuer: string;
  // Potentially other fields like reference, etc.
}

interface LockRequest {
  workflowId: string;
  owner: string;
  amount: string;
  asset: AssetId;
  targetDomain: string;
  recipient: string;
}

interface LockedAsset {
  workflowId: string;
  owner: string;
  amount: string;
  asset: AssetId;
  targetDomain: string;
  recipient: string;
}

interface MintRequest {
  workflowId: string;
  recipient: string;
  lock: LockedAsset;
}

interface MintedAsset {
  workflowId: string;
  owner: string;
  amount: string;
  originalAsset: AssetId;
  sourceDomain: string;
}

interface BurnRequest {
  workflowId: string;
  owner: string;
  wrappedAssetCid: string; // ContractId of MintedAsset
}

interface BurnedReceipt {
  workflowId: string;
  owner: string;
  amount: string;
  originalAsset: AssetId;
  sourceDomain: string;
}

interface UnlockRequest {
  workflowId: string;
  owner: string;
  receipt: BurnedReceipt;
}

type InFlightTransfer = {
  workflowId: string;
  status: string;
  amount: string;
  assetSymbol: string;
  source: string;
  destination: string;
  lockRequest?: Contract<LockRequest>;
  lockedAsset?: Contract<LockedAsset>;
  mintRequest?: Contract<MintRequest>;
  mintedAsset?: Contract<MintedAsset>;
  burnRequest?: Contract<BurnRequest>;
  burnedReceipt?: Contract<BurnedReceipt>;
  unlockRequest?: Contract<UnlockRequest>;
};

const getTransferStatus = (transfer: Omit<InFlightTransfer, 'status'>): string => {
  if (transfer.unlockRequest) return "Unlocking on Source Domain";
  if (transfer.burnedReceipt) return "Burn Confirmed, Awaiting Unlock";
  if (transfer.burnRequest) return "Burning Wrapped Asset on Target";
  if (transfer.mintedAsset) return "Bridged: Wrapped Asset Minted";
  if (transfer.mintRequest) return "Minting Wrapped Asset on Target";
  if (transfer.lockedAsset) return "Asset Locked on Source";
  if (transfer.lockRequest) return "Lock Requested on Source";
  return "Unknown";
};

const shortenParty = (party: string | undefined): string => {
  if (!party) return 'N/A';
  const parts = party.split('::');
  return parts[0];
};

const BridgeWidget: React.FC = () => {
  const party = useParty();

  const lockRequests = useStreamQueries<LockRequest>({[LOCK_REQUEST_TID]: {owner: party}}).contracts;
  const lockedAssets = useStreamQueries<LockedAsset>({[LOCKED_ASSET_TID]: {owner: party}}).contracts;
  const mintRequests = useStreamQueries<MintRequest>({[MINT_REQUEST_TID]: {recipient: party}}).contracts;
  const mintedAssets = useStreamQueries<MintedAsset>({[MINTED_ASSET_TID]: {owner: party}}).contracts;
  const burnRequests = useStreamQueries<BurnRequest>({[BURN_REQUEST_TID]: {owner: party}}).contracts;
  const burnedReceipts = useStreamQueries<BurnedReceipt>({[BURNED_RECEIPT_TID]: {owner: party}}).contracts;
  const unlockRequests = useStreamQueries<UnlockRequest>({[UNLOCK_REQUEST_TID]: {owner: party}}).contracts;

  const inFlightTransfers = useMemo<InFlightTransfer[]>(() => {
    const transfers = new Map<string, Omit<InFlightTransfer, 'status' | 'assetSymbol' | 'source' | 'destination'>>();

    const allContracts = [
      ...lockRequests, ...lockedAssets, ...mintRequests, ...mintedAssets,
      ...burnRequests, ...burnedReceipts, ...unlockRequests
    ];

    for (const contract of allContracts) {
      const workflowId = contract.payload.workflowId;
      if (!workflowId) continue;

      const existing = transfers.get(workflowId) || { workflowId, amount: "0.0" };

      if (contract.templateId.endsWith("LockRequest")) existing.lockRequest = contract as Contract<LockRequest>;
      if (contract.templateId.endsWith("LockedAsset")) existing.lockedAsset = contract as Contract<LockedAsset>;
      if (contract.templateId.endsWith("MintRequest")) existing.mintRequest = contract as Contract<MintRequest>;
      if (contract.templateId.endsWith("MintedAsset")) existing.mintedAsset = contract as Contract<MintedAsset>;
      if (contract.templateId.endsWith("BurnRequest")) existing.burnRequest = contract as Contract<BurnRequest>;
      if (contract.templateId.endsWith("BurnedReceipt")) existing.burnedReceipt = contract as Contract<BurnedReceipt>;
      if (contract.templateId.endsWith("UnlockRequest")) existing.unlockRequest = contract as Contract<UnlockRequest>;

      // Extract details from the earliest contract available
      if (!existing.amount || existing.amount === "0.0") {
        existing.amount = contract.payload.amount || "0.0";
      }

      transfers.set(workflowId, existing);
    }

    return Array.from(transfers.values()).map(t => {
      const definitiveContract = t.lockedAsset || t.lockRequest || t.mintedAsset || t.burnedReceipt || t.unlockRequest;
      const assetInfo = definitiveContract?.payload.asset || definitiveContract?.payload.originalAsset;
      const recipient = t.lockRequest?.payload.recipient || t.lockedAsset?.payload.recipient;

      return {
        ...t,
        status: getTransferStatus(t),
        assetSymbol: assetInfo?.symbol || 'N/A',
        source: shortenParty(t.lockRequest?.payload.owner || t.lockedAsset?.payload.owner),
        destination: shortenParty(recipient),
      };
    }).sort((a, b) => a.workflowId.localeCompare(b.workflowId));
  }, [lockRequests, lockedAssets, mintRequests, mintedAssets, burnRequests, burnedReceipts, unlockRequests]);

  const isLoading = [
    lockRequests, lockedAssets, mintRequests, mintedAssets,
    burnRequests, burnedReceipts, unlockRequests
  ].some(query => query.loading);


  return (
    <div className="bridge-widget-container">
      <h3>In-Flight Cross-Chain Transfers</h3>
      {isLoading && <p>Loading transfers...</p>}
      {!isLoading && inFlightTransfers.length === 0 && (
        <p>No active cross-domain transfers found for your party.</p>
      )}
      {!isLoading && inFlightTransfers.length > 0 && (
        <table className="bridge-table">
          <thead>
            <tr>
              <th>Workflow ID</th>
              <th>Amount</th>
              <th>Asset</th>
              <th>From</th>
              <th>To</th>
              <th>Status</th>
            </tr>
          </thead>
          <tbody>
            {inFlightTransfers.map(transfer => (
              <tr key={transfer.workflowId}>
                <td title={transfer.workflowId} className="workflow-id">{transfer.workflowId.substring(0, 8)}...</td>
                <td>{transfer.amount}</td>
                <td>{transfer.assetSymbol}</td>
                <td>{transfer.source}</td>
                <td>{transfer.destination}</td>
                <td>
                  <span className={`status-pill status-${transfer.status.split(' ')[0].toLowerCase()}`}>
                    {transfer.status}
                  </span>
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      )}
      <style>{`
        .bridge-widget-container {
          font-family: sans-serif;
          background-color: #f9f9f9;
          border-radius: 8px;
          padding: 16px 24px;
          border: 1px solid #e0e0e0;
        }
        .bridge-widget-container h3 {
          margin-top: 0;
          color: #333;
        }
        .bridge-table {
          width: 100%;
          border-collapse: collapse;
          font-size: 0.9em;
        }
        .bridge-table th, .bridge-table td {
          padding: 12px 8px;
          text-align: left;
          border-bottom: 1px solid #ddd;
        }
        .bridge-table th {
          font-weight: 600;
          color: #555;
        }
        .bridge-table tbody tr:hover {
          background-color: #f1f1f1;
        }
        .workflow-id {
          font-family: monospace;
          cursor: help;
        }
        .status-pill {
          display: inline-block;
          padding: 4px 10px;
          border-radius: 12px;
          font-size: 0.8em;
          font-weight: 500;
          color: #fff;
        }
        .status-lock { background-color: #f0ad4e; }
        .status-asset { background-color: #f0ad4e; }
        .status-minting { background-color: #5bc0de; }
        .status-bridged { background-color: #5cb85c; }
        .status-burning { background-color: #d9534f; }
        .status-burn { background-color: #d9534f; }
        .status-unlocking { background-color: #337ab7; }
        .status-unknown { background-color: #777; }
      `}</style>
    </div>
  );
};

export default BridgeWidget;