import React from 'react';
import { useStreamQueries } from "@c7/react";
import { ContractId } from '@c7/dapp';

// NOTE: These types would typically be auto-generated by `dpm codegen-js`
// from the Daml models. We define them here for illustrative purposes.
// We'll assume a `Bridge.V1` module in Daml.
export interface LockedAsset {
  owner: string;
  notary: string;
  transferId: string;
  sourceDomain: string;
  targetDomain: string;
  recipient: string;
  assetSymbol: string;
  assetQuantity: string;
  lockTime: string; // ISO 8601 timestamp
}

export interface MintRequest {
  recipient: string;
  notary: string;
  transferId: string;
  sourceLockCid: ContractId<LockedAsset>;
  sourceDomain: string;
  targetDomain: string;
  assetSymbol: string;
  assetQuantity: string;
}

export interface BurnRequest {
  owner: string;
  notary: string;
  transferId: string;
  sourceDomain: string;
  targetDomain: string;
  assetSymbol: string;
  assetQuantity: string;
  burnTime: string; // ISO 8601 timestamp
}

export interface UnlockRequest {
  owner: string;
  notary: string;
  transferId: string;
  sourceDomain: string;
  targetDomain: string;
  assetSymbol: string;
  assetQuantity: string;
}

// A unified view model for a single cross-chain transfer
type InFlightTransfer = {
  transferId: string;
  status: 'Locked' | 'Minting' | 'Burned' | 'Unlocking' | 'Unknown';
  sourceDomain: string;
  targetDomain: string;
  owner: string;
  recipient: string;
  assetSymbol: string;
  assetQuantity: string;
  timestamp: string;
};

// --- Helper Functions ---

const getStatus = (
  isLocked: boolean,
  isMinting: boolean,
  isBurned: boolean,
  isUnlocking: boolean
): InFlightTransfer['status'] => {
  if (isUnlocking) return 'Unlocking';
  if (isBurned) return 'Burned';
  if (isMinting) return 'Minting';
  if (isLocked) return 'Locked';
  return 'Unknown';
};

const StatusBadge: React.FC<{ status: InFlightTransfer['status'] }> = ({ status }) => {
  const style: React.CSSProperties = {
    padding: '4px 8px',
    borderRadius: '12px',
    color: 'white',
    fontSize: '0.8rem',
    fontWeight: 600,
    textTransform: 'uppercase',
  };

  const statusInfo = {
    Locked: { label: "Locked", color: "#f0ad4e" },
    Minting: { label: "Minting", color: "#337ab7" },
    Burned: { label: "Burned", color: "#d9534f" },
    Unlocking: { label: "Unlocking", color: "#5cb85c" },
    Unknown: { label: "Unknown", color: "#777" },
  };

  return (
    <span style={{ ...style, backgroundColor: statusInfo[status].color }}>
      {statusInfo[status].label}
    </span>
  );
};


// --- Main Component ---

export const BridgeWidget: React.FC = () => {
  const lockedAssets = useStreamQueries<LockedAsset>({ template: "Bridge.V1:LockedAsset" });
  const mintRequests = useStreamQueries<MintRequest>({ template: "Bridge.V1:MintRequest" });
  const burnRequests = useStreamQueries<BurnRequest>({ template: "Bridge.V1:BurnRequest" });
  const unlockRequests = useStreamQueries<UnlockRequest>({ template: "Bridge.V1:UnlockRequest" });

  const transfers = React.useMemo<InFlightTransfer[]>(() => {
    const transferMap = new Map<string, Partial<InFlightTransfer>>();

    // Process contracts in reverse order of the workflow to catch the latest state
    unlockRequests.contracts.forEach(({ payload }) => {
      transferMap.set(payload.transferId, {
        ...transferMap.get(payload.transferId),
        ...payload,
        owner: payload.owner,
        recipient: transferMap.get(payload.transferId)?.recipient ?? payload.owner, // Recipient is not on UnlockRequest, so we keep it if already set
      });
    });

    burnRequests.contracts.forEach(({ payload }) => {
      transferMap.set(payload.transferId, {
        ...transferMap.get(payload.transferId),
        ...payload,
        timestamp: payload.burnTime,
      });
    });

    mintRequests.contracts.forEach(({ payload }) => {
      transferMap.set(payload.transferId, {
        ...transferMap.get(payload.transferId),
        ...payload,
        owner: transferMap.get(payload.transferId)?.owner ?? payload.recipient, // Owner might not be on mint request
      });
    });

    lockedAssets.contracts.forEach(({ payload }) => {
      // Only add if it's not already in a later stage
      if (!transferMap.has(payload.transferId)) {
        transferMap.set(payload.transferId, { ...payload, timestamp: payload.lockTime });
      } else {
        // Enrich existing entry with data from lock contract if missing
        const existing = transferMap.get(payload.transferId)!;
        if (!existing.owner) existing.owner = payload.owner;
        if (!existing.recipient) existing.recipient = payload.recipient;
        if (!existing.timestamp) existing.timestamp = payload.lockTime;
      }
    });

    const transferSet = new Set(
      [
        ...lockedAssets.contracts,
        ...mintRequests.contracts,
        ...burnRequests.contracts,
        ...unlockRequests.contracts
      ].map(c => c.payload.transferId)
    );

    const allTransfers = Array.from(transferSet).map(transferId => {
      const isLocked = lockedAssets.contracts.some(c => c.payload.transferId === transferId);
      const isMinting = mintRequests.contracts.some(c => c.payload.transferId === transferId);
      const isBurned = burnRequests.contracts.some(c => c.payload.transferId === transferId);
      const isUnlocking = unlockRequests.contracts.some(c => c.payload.transferId === transferId);

      const details = transferMap.get(transferId);

      return {
        transferId: transferId,
        status: getStatus(isLocked, isMinting, isBurned, isUnlocking),
        sourceDomain: details?.sourceDomain ?? 'N/A',
        targetDomain: details?.targetDomain ?? 'N/A',
        owner: details?.owner ?? 'N/A',
        recipient: details?.recipient ?? 'N/A',
        assetSymbol: details?.assetSymbol ?? 'N/A',
        assetQuantity: details?.assetQuantity ?? '0.0',
        timestamp: details?.timestamp ?? new Date(0).toISOString(),
      };
    });

    // Sort by timestamp descending
    return allTransfers.sort((a, b) => new Date(b.timestamp).getTime() - new Date(a.timestamp).getTime());
  }, [lockedAssets.contracts, mintRequests.contracts, burnRequests.contracts, unlockRequests.contracts]);

  const isLoading =
    lockedAssets.loading ||
    mintRequests.loading ||
    burnRequests.loading ||
    unlockRequests.loading;

  return (
    <div style={styles.container}>
      <h2 style={styles.header}>In-Flight Bridge Transfers</h2>
      {isLoading ? (
        <p style={styles.centeredText}>Loading transfer history...</p>
      ) : transfers.length === 0 ? (
        <p style={styles.centeredText}>No active transfers found.</p>
      ) : (
        <table style={styles.table}>
          <thead>
            <tr>
              <th style={styles.th}>Transfer ID</th>
              <th style={styles.th}>Status</th>
              <th style={styles.th}>Direction</th>
              <th style={styles.th}>Asset</th>
              <th style={styles.th}>Amount</th>
              <th style={styles.th}>Timestamp</th>
            </tr>
          </thead>
          <tbody>
            {transfers.map((t) => (
              <tr key={t.transferId} style={styles.tr}>
                <td style={{...styles.td, fontFamily: 'monospace', fontSize: '0.8rem'}} title={t.transferId}>
                  {t.transferId.substring(0, 8)}...
                </td>
                <td style={styles.td}><StatusBadge status={t.status} /></td>
                <td style={styles.td}>{t.sourceDomain} → {t.targetDomain}</td>
                <td style={styles.td}>{t.assetSymbol}</td>
                <td style={{...styles.td, textAlign: 'right'}}>{parseFloat(t.assetQuantity).toLocaleString()}</td>
                <td style={styles.td}>{new Date(t.timestamp).toLocaleString()}</td>
              </tr>
            ))}
          </tbody>
        </table>
      )}
    </div>
  );
};

const styles: { [key: string]: React.CSSProperties } = {
  container: {
    fontFamily: "Arial, sans-serif",
    backgroundColor: "#f9f9f9",
    padding: "20px",
    borderRadius: "8px",
    boxShadow: "0 2px 4px rgba(0,0,0,0.1)",
    maxWidth: "1000px",
    margin: "20px auto",
  },
  header: {
    color: "#333",
    borderBottom: "2px solid #eee",
    paddingBottom: "10px",
    marginBottom: "20px",
  },
  centeredText: {
    textAlign: "center",
    color: "#666",
    padding: "20px",
  },
  table: {
    width: "100%",
    borderCollapse: "collapse",
  },
  th: {
    backgroundColor: "#f2f2f2",
    color: "#333",
    fontWeight: "bold",
    padding: "12px 15px",
    textAlign: "left",
    borderBottom: "2px solid #ddd",
  },
  tr: {
    borderBottom: "1px solid #eee",
  },
  td: {
    padding: "12px 15px",
    color: "#555",
    verticalAlign: "middle",
  },
};

export default BridgeWidget;